### ISSUE TITLE
Overriding filename?

### ISSUE THREAD

**Issue by josephguillaume** [EdJoPaTo/website-stalker#179]
**Describe your goal**
I have a url that includes a long query string.
The run fails with `File name too long (os error 36)`

**Expected**
The easiest option would seem to be allowing a custom filename to be defined for a given url?
E.g. with a new key `filename`

Thanks for considering it!

**Comment by EdJoPaTo** [comment]
Thank you for the report! Yeah, I see the point.

The basic idea was to prevent manual handling of filenames to allow them to be automagically handled. Overriding the generated filename should be possible with these file handling operations I think.

Not sure if there is a better option. 🤔
Hashing might result in conflicts so a strict filename might be the most error proof option.

**Comment by Teufelchen1** [comment]
Hi! 
@josephguillaume I opened a PR implementing your idea like this:

```yaml
sites:
  - url: "https://edjopato.de/api?token=0123456789&action=hack%20the%20planet"
    filename: de-edjopato-api-planet-hack
```

Would that work for you?
