### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by EdJoPaTo** [EdJoPaTo/website-stalker#2]
Utilize caches to not transfer everything on every run. Http 304 Not Modified is there for a reason and might also be used here.

Looks promising:

https://github.com/kornelski/rusty-http-cache-semantics/
https://crates.io/crates/http-cache-semantics

```toml
[dependencies.http-cache-semantics]
version = "0.9"
features = ["reqwest"]
```
