### ISSUE TITLE
Allow grouping of links

### ISSUE THREAD

**Issue by rEnr3n** [EdJoPaTo/website-stalker#42]
**Is your feature request related to a problem? Please describe.**
I'm following multiple links and I apply the same editors for all of them. Below is an example:
```
---
from: email@address
sites:
  - url: https://example.com/one
    extension: md
    editors:
      - html_markdownify
  - url: https://example.com/two
    extension: md
    editors:
      - html_markdownify
```

**Describe the solution you'd like**
I want it shortened to something like this:
```
---
from: email@address
sites:
  - urls:
      - https://example.com/one
      - https://example.com/two
    extension: md
    editors:
      - html_markdownify
```

**Describe alternatives you've considered**

**Additional context**
